name: 'Run in Nodejs'
on:
  push:
    branches:
      - master
jobs:
  Run:
    runs-on: Ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: 'Use Nodejs'
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: 'build & run'
        shell: bash
        env:
          BILICOOKIES: ${{ secrets.COOKIES }}
        run: |
          npm run build
          npm run start