name: 'Run in Nodejs'
on:
  push:
    branches:
      - master
  workflow_dispatch:
    input:
      launch:
        des: 'launch this workflow'
      close:
        des: 'close this workflow'
jobs:
  Run:
    runs-on: Ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Nodejs'
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: 'build & run'
        shell: bash
        env:
          BILI: ${{ secrets.BILI_COOKIES }}
        run: |
          npm run build
          npm run start