name: 'Run in Nodejs'
on: [workflow_dispatch]
jobs:
  Run:
    runs-on: Ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Nodejs'
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.4
      - name: 'install && run'
        shell: bash
        env:
          BILI: ${{ secrets.BILI_COOKIES }}
          TOKEN: ${{ secrets.ACCESS_TOKEN}}
          REPO: ${{ GITHUB_REPOSITORY }}
        run: |
          npm run server-install
          npm run server